swagger: "2.0"
info:
  description: "Blog Post App REST API"
  version: "1.0.0"
  title: "Blog Post API"
host: "localhost:9080"
basePath: "/api/v1"
tags:
  - name: "blogpost"
    description: "Everything about your blog posts"
  - name: "hashtag"
    description: "Everything about the hash tags"
schemes:
  - "https"
  - "http"
paths:
  /posts:
    get:
      tags:
        - "blogpost"
      summary: "Load all blog posts"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Posts were loaded successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/BlogPost"
    post:
      tags:
        - "blogpost"
      summary: "Create a blog post"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "newPost"
          schema:
            $ref: "#/definitions/BlogPost"
      responses:
        "201":
          description: "Post was created successfully"
          schema:
            $ref: "#/definitions/BlogPost"
          headers:
            "Location":
              type: "string"
              description: URL to the newly created blog post
        "422":
          description: "Blog post is invalid"
definitions:
  BlogPost:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      title:
        type: "string"
        minLength: 3
      content:
        type: "string"
        minLength: 10
      timestamp:
        type: "string"
        format: "date-time"
        readOnly: true
      author:
        type: "string"
        readOnly: true
    required:
      - title
      - content
  HashTag:
    type: "object"
    properties:
      name:
        type: "string"
        readOnly: true
      description:
        type: "string"
        minLength: 1
    required:
      - description
