# always valid, but can be overwritten in profiles
spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
blog-app:
  title: Blog Post App from Ralf
cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:*}
    credentials: ${CORS_ALLOWED_CREDENTIALS:false}
springdoc:
  swagger-ui:
    enabled: false
