# valid, if "dev" profile is enabled
blog-app:
  title: Blog Post App in DEV Stage!
server:
  port: 9080
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:h2:./.local-db/data
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:9080/h2-console (leave username and password empty)
management:
  endpoints:
    web:
      exposure:
        include: '*'
        #health,info,beans,metrics,startup
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: Manually Configured API
        url: /blogpost-swagger.yml
      - name: Code-Generated API
        url: /v3/api-docs
    urls-primary-name: Manually Configured API
  paths-to-match:
    - /api/**
